-- FIX: Add missing columns to PRODUCTS table if they don't exist
DO $$
BEGIN
    -- Add 'is_featured'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'is_featured') THEN
        ALTER TABLE products ADD COLUMN is_featured BOOLEAN DEFAULT false;
    END IF;

    -- Add 'stock_status'
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'stock_status') THEN
        ALTER TABLE products ADD COLUMN stock_status TEXT DEFAULT 'in_stock';
    END IF;

    -- Add 'created_at' (Critical for sorting)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'created_at') THEN
        ALTER TABLE products ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
    END IF;
    
    -- Add 'image_url' (Just in case)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'image_url') THEN
        ALTER TABLE products ADD COLUMN image_url TEXT;
    END IF;
     -- Add 'category' (Just in case)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'category') THEN
        ALTER TABLE products ADD COLUMN category TEXT;
    END IF;
END $$;

-- Ensure ORDERS table exists
CREATE TABLE IF NOT EXISTS orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT, 
  product_price NUMERIC,
  status TEXT DEFAULT 'paid',
  payment_method TEXT DEFAULT 'Credit Card',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Ensure USER_SERVICES table exists
CREATE TABLE IF NOT EXISTS user_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  type TEXT, 
  plan_name TEXT,
  details JSONB, 
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Force Schema Cache Reload (metadata call)
NOTIFY pgrst, 'reload config';
