-- ⚠️ HARD RESET: Drops tables to ensure clean schema
-- Run this in Supabase SQL Editor

-- 1. Drop existing tables (Reverse order of dependencies)
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS user_services CASCADE;

-- 2. Re-create PRODUCTS table (Correct Schema)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC,
  category TEXT,
  image_url TEXT,
  stock_status TEXT DEFAULT 'in_stock',
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Re-create ORDERS table
CREATE TABLE orders (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  product_id BIGINT REFERENCES products(id),
  product_name TEXT, 
  product_price NUMERIC,
  status TEXT DEFAULT 'paid',
  payment_method TEXT DEFAULT 'Credit Card',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Re-create USER_SERVICES table
CREATE TABLE user_services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  type TEXT,
  plan_name TEXT,
  details JSONB,
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. Enable RLS (Security)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User Own Orders" ON orders FOR ALL USING (auth.uid() = user_id);

ALTER TABLE user_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User Own Services" ON user_services FOR ALL USING (auth.uid() = user_id);

-- 6. Refresh Cache
NOTIFY pgrst, 'reload config';
