
-- Fix cart_items product_id type
-- 1. Alter product_id to be UUID
-- NOTE: We must cast existing data, but since it's likely empty or invalid if it was mismatched, we'll try straight conversion or drop/recreate.

-- Option 1: Drop/Recreate (Safest given it's a dev env issue)
DROP TABLE IF EXISTS public.cart_items CASCADE;

CREATE TABLE public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT REFERENCES public.carts(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own cart items"
ON public.cart_items FOR SELECT
TO authenticated
USING (
    cart_id IN (
        SELECT id FROM public.carts WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Users can insert into their own cart"
ON public.cart_items FOR INSERT
TO authenticated
WITH CHECK (
    cart_id IN (
        SELECT id FROM public.carts WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Users can update their own cart items"
ON public.cart_items FOR UPDATE
TO authenticated
USING (
    cart_id IN (
        SELECT id FROM public.carts WHERE user_id = auth.uid()
    )
);

CREATE POLICY "Users can delete their own cart items"
ON public.cart_items FOR DELETE
TO authenticated
USING (
    cart_id IN (
        SELECT id FROM public.carts WHERE user_id = auth.uid()
    )
);
