import os
import datetime
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from app.models import Ticket

REPORTS_DIR = "app/reports"

def generate_ticket_report(ticket: Ticket) -> str:
    """
    Generate a PDF report for a resolved ticket.
    Returns the filename.
    """
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)

    filename = f"ticket_{ticket.id}_report.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = styles["Title"]
    story.append(Paragraph(f"Ticket Resolution Report #{ticket.id}", title_style))
    story.append(Spacer(1, 12))

    # Metadata Table
    data = [
        ["Field", "Value"],
        ["ID", str(ticket.id)],
        ["Title", ticket.title],
        ["Status", "Closed"],  # Assumes closed
        ["Category", ticket.category or "N/A"],
        ["Priority", ticket.priority],
        ["Department", ticket.department or "N/A"],
        ["Created", ticket.created_at.strftime("%Y-%m-%d %H:%M")],
        ["Closed", datetime.datetime.now().strftime("%Y-%m-%d %H:%M")]
    ]

    t = Table(data, colWidths=[100, 350])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#8c2bee')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # Description
    story.append(Paragraph("Description", styles["Heading2"]))
    story.append(Paragraph(ticket.description, styles["Normal"]))
    story.append(Spacer(1, 24))

    # AI Analysis
    story.append(Paragraph("AI Analysis", styles["Heading2"]))
    
    ai_priority = ticket.ai_priority or "N/A"
    ai_reasoning = ticket.ai_reasoning or "No analysis performed."
    
    story.append(Paragraph(f"<b>AI Priority:</b> {ai_priority}", styles["Normal"]))
    story.append(Spacer(1, 6))
    story.append(Paragraph(f"<b>Reasoning & Risk:</b>", styles["Normal"]))
    story.append(Paragraph(ai_reasoning.replace("\n", "<br/>"), styles["Normal"]))
    story.append(Spacer(1, 36))

    # Footer
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.gray)
    story.append(Paragraph("Generated by IntelliFlow Copilot • Automated RPA System", footer_style))

    doc.build(story)
    return filename

def send_notification(ticket: Ticket, action: str) -> bool:
    """Mock notification sender"""
    print(f"\n📧 EMAIL SENT TO: {ticket.department or 'Admin'}@company.com")
    print(f"Subject: Ticket #{ticket.id} Update - {action}")
    print(f"Body: The ticket '{ticket.title}' has been processed. Action: {action}.\n")
    return True

def log_automation_action(ticket_id: int, action: str, details: str, session) -> None:
    """Log action to console (mocking DB log)"""
    timestamp = datetime.datetime.now().isoformat()
    print(f"🤖 RPA LOG [{timestamp}]: Ticket #{ticket_id} | Action: {action} | Details: {details}")

def close_ticket_workflow(ticket_id: int, session) -> Dict[str, Any]:
    """
    Orchestrates the ticket closure workflow.
    """
    ticket = session.get(Ticket, ticket_id)
    if not ticket:
        return {"status": "error", "message": "Ticket not found"}

    # 1. Update Status
    ticket.status = "Closed"
    session.add(ticket)
    session.commit()
    session.refresh(ticket)
    
    actions = ["Status Updated to Closed"]
    log_automation_action(ticket.id, "UPDATE_STATUS", "Set to Closed", session)

    # 2. Generate Report
    try:
        pdf_filename = generate_ticket_report(ticket)
        actions.append(f"Generated Report: {pdf_filename}")
        log_automation_action(ticket.id, "GENERATE_PDF", pdf_filename, session)
        pdf_url = f"/reports/{pdf_filename}"
    except Exception as e:
        print(f"Error generating PDF: {e}")
        pdf_filename = None
        pdf_url = None

    # 3. Send Notification
    send_notification(ticket, "Closed & Resolved")
    actions.append("Sent Email Notification")
    log_automation_action(ticket.id, "SEND_EMAIL", "Closure notification sent", session)

    return {
        "status": "success",
        "ticket_id": ticket.id,
        "pdf_filename": pdf_filename,
        "pdf_url": pdf_url,
        "actions_completed": actions
    }
